server:
  port: 8080

spring:
  main:
    allow-circular-references: true
  application:
    name: uninotes-india
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://127.0.0.1:27017/uninotes}
      database: uninotes
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

app:
  upload:
    dir: ${APP_UPLOAD_DIR:uploads}
